### ISSUE TITLE
`lerna run --no-bail` throws error

### ISSUE THREAD

**Issue by alex-taxiera** [ghiscoding/lerna-lite#149]
### Describe the bug

Migrating to npm workspaces + lerna-lite from lerna and was trying to run my same `lint` command with `--no-bail` flag.
The command seems to work completely but throws an error after the success report. Tried the same command without the `--no-bail` flag and it passed just fine.

### Reproduction

run any command with `--no-bail`

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "stream": true,
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv {
0 silly argv   _: [ 'run' ],
0 silly argv   bail: false,
0 silly argv   lernaVersion: '1.1.1',
0 silly argv   '$0': '/Users/alex/Source/eris-boiler/node_modules/.bin/lerna',
0 silly argv   script: 'lint'
0 silly argv }
1 notice cli v1.1.1
2 verbose rootPath /Users/alex/Source/eris-boiler
3 info versioning independent
4 verbose project packages packages/*
5 info Executing command in 3 packages: "npm run lint"
6 verbose Topological npm run lint
7 success run Ran npm script 'lint' in 3 packages in 8.0s:
8 error TypeError: Cannot read properties of undefined (reading 'name')
8 error     at /Users/alex/Source/eris-boiler/node_modules/@lerna-lite/run/dist/run-command.js:119:66
8 error     at Array.forEach (<anonymous>)
8 error     at /Users/alex/Source/eris-boiler/node_modules/@lerna-lite/run/dist/run-command.js:113:25
```
</p></details>

### Environment Info

```shell
| Executable        | Version |
| ----------------- | ------- |
| `lerna --version` | 1.1.1 |
| `npm --version`   | 8.2.0 |
| `node --version`  | 16.13.1 |
---
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/lerna-lite/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/ghiscoding/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
The code is the same as the original Lerna except that I rewrote it in TypeScript and I never used that flag, so I can't provide much help on this,. I would suggest to look at Lerna's [issues](https://github.com/lerna/lerna/issues) to see if you can find anything that might help there. Or troubleshoot and create a Pull Request if you ever come up with a fix. The option seems to be used at this line in the run command

https://github.com/ghiscoding/lerna-lite/blob/c6f3a3426b2c6c49efe69408f3094e3071e989d9/packages/run/src/run-command.ts#L105-L112

the lerna debug log file that you provided might be helpful though, it says that it can't read `name`, can you go and find out what that object it's trying to resolves to?

**Comment by ghiscoding** [comment]
looking at the shipped code on [unpkg](https://unpkg.com/browse/@lerna-lite/run@1.1.1/dist/run-command.js), the line number don't match totally but it seems to say that the `result.pkg` is undefined and so `result.pkg.name` throws the error. 

![image](https://user-images.githubusercontent.com/643976/167321466-c4c3587e-a685-46b3-9fdd-b66174d96ca8.png)

the only way to troubleshoot this would be for you to edit that JS file and add a console log of the `result`, the object structure might be different compare to what it expect.

**Comment by alex-taxiera** [comment]
I tried checking `lerna` for this exact code block but I could not find it. Modified the code with a log like you suggested, not sure exactly what `result` is supposed to be, but it looks like it's completely missing `pkg` in my use case.

modified code:
```js
if (!this.bail) {
    results.forEach((result) => {
        console.log(result)
        if (result === null || result === void 0 ? void 0 : result.failed) {
            this.logger.error('', `- ${result.pkg.name}`);
        }
        else {
            this.logger.success('', ` - ${result.pkg.name}`);
        }
    });
}
```
result from the log:
```js
{
  command: 'npm run lint',
  escapedCommand: 'npm run lint',
  exitCode: 0,
  stdout: '\n' +
    '> @hephaestus/utils@0.0.0 lint\n' +
    '> eslint src\n' +
    '\n' +
    '\n' +
    '/Users/alex/Source/eris-boiler/packages/utils/src/type.ts\n' +
    '   1:44  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any\n' +
    '  16:13  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any\n' +
    '\n' +
    '✖ 2 problems (0 errors, 2 warnings)\n',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by ghiscoding** [comment]
Actually it's probably because I replicated this open [PR](https://github.com/lerna/lerna/pull/2974) from Lerna and that PR was probably not tested properly (it has no unit test for it). That is probably the cause

**Comment by ghiscoding** [comment]
@alex-taxiera 
I found the issue with that PR from Lerna that I merged in Lerna-Lite, so that PR was only supposed to help with showing the package name when user is not using `--stream` (and you are), so if you modify Lerna-Lite JS file from dist folder with the following it should be working as expected. It would be nice to have a confirmation. Thanks

```diff
- if (!this.bail) {
+ if (!this.bail && !this.options.stream) {
        results.forEach((result) => {
          if (result?.failed) {
            this.logger.error('', `- ${result.pkg?.name}`);
          } else {
            this.logger.success('', ` - ${result.pkg?.name}`);
          }
        });
} else {
        this.logger.success('', this.packagesWithScript.map((pkg) => `- ${pkg.name}`).join('\n'));
}
```

**Comment by ghiscoding** [comment]
should be fixed in latest release [1.2.0](https://github.com/ghiscoding/lerna-lite/releases/tag/v1.2.0)
